# Generated by Django 4.1.5 on 2023-09-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_alter_technicianprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='profession',
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techProfession', models.TextField()),
                ('technicianProfession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='technician.technicianprofile')),
            ],
        ),
    ]
