# Generated by Django 4.2.4 on 2023-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_alter_technicianprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
