# Generated by Django 4.1.5 on 2023-09-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_remove_technicianprofile_profession_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='technicianProfession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='technician.technicianprofile'),
        ),
    ]
