# Generated by Django 4.2.4 on 2023-08-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_alter_technicianprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='feedback',
        ),
    ]
