# Generated by Django 4.2.4 on 2023-08-31 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0004_remove_technicianprofile_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
