# Generated by Django 4.2.4 on 2023-08-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technician', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
                ('state_is_ongoing', models.BooleanField(default=True)),
                ('state_show', models.BooleanField(default=True)),
                ('eta_arrival_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('technician_type', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.technicianprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
    ]
