# Generated by Django 4.2.4 on 2023-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='state_is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
