# Generated by Django 4.1.5 on 2023-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
