# Generated by Django 4.2.4 on 2023-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_rating_alter_order_state_is_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eta_arrival_time',
            field=models.IntegerField(default=0),
        ),
    ]
