# Generated by Django 4.1.5 on 2023-08-31 19:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
