# Generated by Django 4.2.4 on 2023-08-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_eta_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_technician',
        ),
    ]
