# Generated by Django 4.2.4 on 2023-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_current_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eta_arrival_time',
            field=models.DateTimeField(default=0),
        ),
    ]
