# Generated by Django 4.2.4 on 2023-08-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_eta_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
