# Generated by Django 4.2.4 on 2023-08-31 19:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
